packages:
  - "."
  - "landing-astro"

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd

ignoredBuiltDependencies:
  - core-js
  - protobufjs
  - unrs-resolver

allowBuilds:
  core-js: false
  esbuild: true
  protobufjs: false
  sharp: true
  unrs-resolver: false
  workerd: true
